### ISSUE TITLE
New meteor update breaking

### ISSUE THREAD

**Issue by Nakroma** [sebakerckhof/meteor-minifiers-autoprefix#6]
Hey,  
Since updating meteor to 1.4.1.1 I get this error on starting the server. When I remove the package it works again (also removing scss from fourseven of course)

> => Errors prevented startup:
> 
>    While minifying app stylesheet:
>    module.js:325:15: Cannot find module 'source-map-url'
>    at Function.Module._resolveFilename (module.js:325:15)
>    at Function.Module._load (module.js:276:25)
>    at Module.require (module.js:353:17)
>    at require (internal/module.js:12:17)
>    at Object.<anonymous>
>    (C:\Users\Nakroma\AppData\Local.meteor\packages\seba_minifiers-autoprefixer\1.0.1\plugin.minifyStdCSS.os\npm\node_modules\meteor\minifier-css\node_modules\css-stringify\node_modules\css\node_modules\source-map-resolve\lib\source-map-resolve-node.js:4:24)
>    at Module._compile (module.js:409:26)
>    at Object.Module._extensions..js (module.js:416:10)
>    at Module.load (module.js:343:32)
>    at Module.Mp.load
>    (C:\Users\Nakroma\AppData\Local.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
>    at Function.Module._load (module.js:300:12)
>    at Module.require (module.js:353:17)
>    at require (internal/module.js:12:17)
>    at Object.<anonymous>
>    (C:\Users\Nakroma\AppData\Local.meteor\packages\seba_minifiers-autoprefixer\1.0.1\plugin.minifyStdCSS.os\npm\node_modules\meteor\minifier-css\node_modules\css-stringify\node_modules\css\lib\stringify\source-map-support.js:8:24)
>    at Module._compile (module.js:409:26)
>    at Object.Module._extensions..js (module.js:416:10)
>    at Module.load (module.js:343:32)
>    at Module.Mp.load
>    (C:\Users\Nakroma\AppData\Local.meteor\packages\meteor-tool\1.4.1_1\mt-os.windows.x86_32\dev_bundle\lib\node_modules\reify\node\runtime.js:16:23)
>    at Function.Module._load (module.js:300:12)
>    at Module.require (module.js:353:17)
>    at require (internal/module.js:12:17)
>    at Object.module.exports
>    (C:\Users\Nakroma\AppData\Local.meteor\packages\seba_minifiers-autoprefixer\1.0.1\plugin.minifyStdCSS.os\npm\node_modules\meteor\minifier-css\node_modules\css-stringify\node_modules\css\lib\stringify\index.js:32:22)
>    at packages/minifyStdCSS_plugin.js:136:33
>    at CssToolsMinifier.processFilesForBundle
>    (packages/minifyStdCSS_plugin.js:49:16)

**Comment by copleykj** [comment]
Issue is super old and I'm not able to reproduced this. If this issue persists, please feel free to reopen.
